# This is a special configuration file to run tests on Travis-CI via
# GitHub notifications when changes are committed.
#
# For technical details, see http://travis-ci.org/

language: python
sudo: false

install:
 - pip install flake8

script:
 - flake8 --ignore E501,E402,E305 .

notifications:
  email: false
